//! Embedded subset faces, installed into egui at boot (ADR 0097).
//!
//! Four faces ship in the wasm bundle as subset TTFs under
//! `crates/reticle-app/assets/fonts/` (regenerated by `scripts/subset-fonts.ps1`):
//! Inter Regular and Medium for UI text (SIL OFL 1.1), `JetBrains Mono` Regular for
//! coordinates and readouts (SIL OFL 1.1), and the Lucide icon font (ISC). Their
//! license notices sit beside them in that directory.
//!
//! [`install`] wires them into three families so any label can inline a glyph
//! from [`crate::theme::icons`]:
//!
//! * `Proportional` = Inter Regular, then Lucide as the icon fallback.
//! * `Monospace` = `JetBrains Mono`, then Lucide.
//! * `Name("ui-medium")` = Inter Medium, then Lucide, for section headers
//!   (see [`ui_medium`]).
//!
//! Lucide carries a [`egui::FontTweak`] so its glyphs, which fill the em box
//! above the baseline, drop onto the surrounding text's optical center instead
//! of floating above it.

use eframe::egui::{self, FontData, FontDefinitions, FontFamily, FontTweak};
use std::sync::Arc;

/// Inter Regular, the proportional UI face.
const INTER_REGULAR: &[u8] = include_bytes!("../../assets/fonts/inter-regular.subset.ttf");
/// Inter Medium, the section-header face.
const INTER_MEDIUM: &[u8] = include_bytes!("../../assets/fonts/inter-medium.subset.ttf");
/// `JetBrains Mono` Regular, the coordinate and readout face.
const JETBRAINS_MONO: &[u8] =
    include_bytes!("../../assets/fonts/jetbrains-mono-regular.subset.ttf");
/// The Lucide icon font, the fallback family for every text family.
const LUCIDE: &[u8] = include_bytes!("../../assets/fonts/lucide.subset.ttf");

/// `font_data` key for Inter Regular.
const INTER_R_KEY: &str = "inter-r";
/// `font_data` key for Inter Medium.
const INTER_M_KEY: &str = "inter-m";
/// `font_data` key for `JetBrains Mono`.
const JBMONO_KEY: &str = "jbmono";
/// `font_data` key for the Lucide icon font.
const LUCIDE_KEY: &str = "lucide";

/// Family name for the medium-weight UI face (`egui::FontFamily::Name`), used by
/// section headers. Callers build the family with [`ui_medium`].
pub const UI_MEDIUM: &str = "ui-medium";

/// The medium-weight UI family (Inter Medium), for section and panel headers.
#[must_use]
pub fn ui_medium() -> FontFamily {
    FontFamily::Name(UI_MEDIUM.into())
}

/// The baseline alignment for Lucide. Its glyphs occupy roughly the full em
/// above the baseline (`yMax` about 0.88 em, `yMin` 0), so a small positive
/// `y_offset_factor` shifts them down onto the text's optical center. Verified
/// visually at Gate 1 (ui-baselines) and tunable there without touching callers.
fn lucide_tweak() -> FontTweak {
    FontTweak {
        scale: 1.0,
        y_offset_factor: 0.12,
        ..FontTweak::default()
    }
}

/// Builds the [`FontDefinitions`] this app installs: the four subset faces wired
/// into the three families, Lucide last in each as the icon fallback. Split out
/// from [`install`] so it can be unit-tested without an `egui::Context`.
///
/// Starts from [`FontDefinitions::empty`]: the app ships only these subset faces,
/// so egui's stock fonts are never referenced (the `default_fonts` offset in
/// ADR 0097). A character in no subset falls back to Lucide, then to nothing.
#[must_use]
pub fn definitions() -> FontDefinitions {
    let mut fonts = FontDefinitions::empty();
    fonts.font_data.insert(
        INTER_R_KEY.to_owned(),
        Arc::new(FontData::from_static(INTER_REGULAR)),
    );
    fonts.font_data.insert(
        INTER_M_KEY.to_owned(),
        Arc::new(FontData::from_static(INTER_MEDIUM)),
    );
    fonts.font_data.insert(
        JBMONO_KEY.to_owned(),
        Arc::new(FontData::from_static(JETBRAINS_MONO)),
    );
    fonts.font_data.insert(
        LUCIDE_KEY.to_owned(),
        Arc::new(FontData::from_static(LUCIDE).tweak(lucide_tweak())),
    );

    fonts.families.insert(
        FontFamily::Proportional,
        vec![INTER_R_KEY.to_owned(), LUCIDE_KEY.to_owned()],
    );
    fonts.families.insert(
        FontFamily::Monospace,
        vec![JBMONO_KEY.to_owned(), LUCIDE_KEY.to_owned()],
    );
    fonts.families.insert(
        ui_medium(),
        vec![INTER_M_KEY.to_owned(), LUCIDE_KEY.to_owned()],
    );
    fonts
}

/// Marker stored in the context once the fonts are installed, so the boot
/// styling hook can call [`install`] every frame while the font atlas is built
/// only once.
#[derive(Clone, Copy, Debug)]
struct Installed;

/// The id under which [`Installed`] is stashed.
fn installed_id() -> egui::Id {
    egui::Id::new("reticle-fonts-installed")
}

/// Installs the subset faces into `ctx`. Idempotent: safe to call every frame
/// from the boot styling hook, since it rebuilds the font atlas only on the
/// first call and is a cheap map lookup thereafter.
pub fn install(ctx: &egui::Context) {
    if ctx
        .data(|d| d.get_temp::<Installed>(installed_id()))
        .is_some()
    {
        return;
    }
    ctx.set_fonts(definitions());
    ctx.data_mut(|d| d.insert_temp(installed_id(), Installed));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn definitions_wire_the_faces_and_families_in_order() {
        let defs = definitions();

        // All four subset faces are registered.
        for key in [INTER_R_KEY, INTER_M_KEY, JBMONO_KEY, LUCIDE_KEY] {
            assert!(defs.font_data.contains_key(key), "missing font key {key}");
        }

        // Each text family lists its face first, then Lucide as the icon fallback.
        assert_eq!(
            defs.families[&FontFamily::Proportional],
            vec![INTER_R_KEY.to_owned(), LUCIDE_KEY.to_owned()],
        );
        assert_eq!(
            defs.families[&FontFamily::Monospace],
            vec![JBMONO_KEY.to_owned(), LUCIDE_KEY.to_owned()],
        );
        assert_eq!(
            defs.families[&ui_medium()],
            vec![INTER_M_KEY.to_owned(), LUCIDE_KEY.to_owned()],
        );
    }

    #[test]
    fn lucide_carries_a_baseline_tweak() {
        let defs = definitions();
        let lucide = &defs.font_data[LUCIDE_KEY];
        assert_ne!(
            lucide.tweak,
            FontTweak::default(),
            "the icon fallback needs a baseline tweak so glyphs sit on the text line",
        );
    }

    #[test]
    fn definitions_start_empty_of_stock_fonts() {
        // Only our four faces, no egui defaults (the default_fonts offset).
        let defs = definitions();
        assert_eq!(defs.font_data.len(), 4);
    }
}
