//! Success bar for open-anything import hardening.
//!
//! Iterates every file in the committed corpus at `corpus/tinytapeout/` through the
//! app's document-open seam ([`reticle_app::open_document_bytes`]) and asserts each
//! one either opens cleanly or fails with a clean, human-readable error, with **no
//! panic and no hang**. For every file that opens, it further asserts the resulting
//! document has finite, sane geometry (a bounded bbox on the framed cell, no
//! coordinate outside the `i32` DBU range that a `Point` can even hold, and a
//! positive database resolution).
//!
//! The corpus mixes a minimized real Tiny Tapeout design with synthesized malformed
//! GDSII (empty, non-GDS, truncated, bad record length, absurd XY count, cyclic and
//! dangling structure references, and a degenerate boundary). It is regenerated by
//! `cargo run -p reticle-io --example gen_tinytapeout_corpus --features corpus-tools`;
//! see `corpus/tinytapeout/NOTICE.md` for provenance.
//!
//! This test is native-only: it reads the corpus from the filesystem, which the
//! `wasm32-unknown-unknown` target has no access to. The seam itself is
//! platform-neutral and is unit-tested in `reticle_app::open` on both targets.

#![cfg(not(target_arch = "wasm32"))]

use reticle_app::{DocFormat, OpenError, open_document_bytes};
use std::path::{Path, PathBuf};

/// The committed corpus directory: two levels up from this crate to the repo root,
/// then `corpus/tinytapeout`.
fn corpus_dir() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .expect("repo root is two levels above the crate")
        .join("corpus")
        .join("tinytapeout")
}

/// Every `.gds` file in the corpus, sorted for a deterministic order.
fn corpus_files() -> Vec<PathBuf> {
    let dir = corpus_dir();
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read corpus dir {}: {e}", dir.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("gds"))
        .collect();
    files.sort();
    files
}

/// Assert the corpus is actually present and non-trivial, so a missing corpus
/// fails loudly rather than passing vacuously.
#[test]
fn corpus_is_present() {
    let files = corpus_files();
    assert!(
        files.len() >= 8,
        "expected the committed corpus to hold at least 8 .gds files, found {} in {}",
        files.len(),
        corpus_dir().display()
    );
    // The minimized real sample must be among them.
    assert!(
        files
            .iter()
            .any(|p| p.file_name().and_then(|n| n.to_str()) == Some("real_tinytapeout_min.gds")),
        "the minimized real Tiny Tapeout sample must be committed"
    );
}

/// The core success bar: every corpus file opens or fails cleanly, no panic, and
/// every opened document has finite, sane geometry.
#[test]
fn every_corpus_file_opens_or_fails_cleanly() {
    let mut opened = 0usize;
    let mut errored = 0usize;

    for path in corpus_files() {
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("<unknown>")
            .to_owned();
        let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {name}: {e}"));

        // Reaching past this call at all proves no panic and no hang: the hardened
        // seam always returns one of the two variants.
        match open_document_bytes(&bytes, DocFormat::Gds) {
            Ok(outcome) => {
                opened += 1;
                assert_sane_document(&outcome, &name);
            }
            Err(err) => {
                errored += 1;
                assert_clean_error(&err, &name);
            }
        }
    }

    // The corpus is designed so both arms are exercised: several malformed files
    // error, and the real + pathological-but-parseable files open.
    assert!(opened >= 1, "at least one corpus file should open");
    assert!(errored >= 1, "at least one corpus file should fail cleanly");
    println!("corpus: {opened} opened, {errored} failed cleanly, 0 panics");
}

/// Every opened document must have finite, usable geometry.
fn assert_sane_document(outcome: &reticle_app::OpenOutcome, name: &str) {
    let doc = &outcome.document;
    assert!(
        doc.cell_count() >= 1,
        "{name}: an opened document must have at least one cell"
    );
    assert!(
        doc.technology().dbu_per_micron > 0,
        "{name}: database resolution must be positive"
    );

    // The framed cell has a finite bbox (or none, for a cell with no drawable
    // geometry, which is still valid). `cell_bbox` is cycle-guarded, so even the
    // cyclic-reference sample returns a finite box rather than recursing forever.
    if let Some(bbox) = doc.cell_bbox(&outcome.top_cell) {
        // `Rect::width`/`height` widen to i64 and never overflow; a finite bbox has
        // non-negative extents.
        assert!(
            bbox.width() >= 0 && bbox.height() >= 0,
            "{name}: framed cell '{}' has a degenerate bbox {bbox:?}",
            outcome.top_cell
        );
        // Corners are within the i32 DBU range by construction (a `Point` holds
        // i32), so the bbox is inherently finite; assert the ordering invariant.
        assert!(
            bbox.min.x <= bbox.max.x && bbox.min.y <= bbox.max.y,
            "{name}: bbox is not normalized: {bbox:?}"
        );
    }

    // Warnings, if any, are well-formed (non-empty summary and detail).
    for w in &outcome.warnings {
        assert!(
            !w.summary.is_empty() && !w.detail.is_empty(),
            "{name}: a warning must carry a summary and a detail"
        );
    }
}

/// A clean error is human-readable and non-empty.
fn assert_clean_error(err: &OpenError, name: &str) {
    let msg = err.to_string();
    assert!(
        !msg.is_empty(),
        "{name}: an error must have a human-readable message"
    );
    // The seam names the format it tried, so the message is actionable.
    assert!(
        msg.contains("GDSII"),
        "{name}: error message should name the format, got: {msg}"
    );
}

/// The minimized real Tiny Tapeout sample opens with real, hierarchical content:
/// several cells, a framed top with a positive-area bbox, and real standard-cell
/// definitions. This is the "real file opens" half of the success bar, made specific.
#[test]
fn real_sample_opens_with_real_content() {
    let path = corpus_dir().join("real_tinytapeout_min.gds");
    let bytes = std::fs::read(&path).expect("real sample present");
    let outcome = open_document_bytes(&bytes, DocFormat::Gds).expect("real sample opens");

    assert!(
        outcome.document.cell_count() >= 2,
        "the minimized design keeps several real cells plus a top"
    );
    let bbox = outcome
        .document
        .cell_bbox(&outcome.top_cell)
        .expect("the framed top cell has a bbox");
    assert!(
        bbox.width() > 0 && bbox.height() > 0,
        "the real sample frames a positive-area cell"
    );
    // A real SkyWater standard cell is present by name.
    assert!(
        outcome
            .document
            .cells()
            .any(|c| c.name.starts_with("sky130_fd_sc_hd__")),
        "the minimized sample keeps real SkyWater cell definitions"
    );
}

/// Bonus: offscreen-render the imported real sample without panicking, when a GPU
/// adapter is available. Skips (and passes) on a machine with no usable adapter,
/// matching the reticle-render GPU tests, so this never blocks a headless run.
#[test]
fn real_sample_renders_offscreen_without_panic() {
    use reticle_model::Camera;
    use reticle_render::{WgpuContext, WgpuRenderer};

    let Some(ctx) = WgpuContext::new_blocking() else {
        eprintln!("no GPU adapter; skipping offscreen render of the real sample");
        return;
    };

    let path = corpus_dir().join("real_tinytapeout_min.gds");
    let bytes = std::fs::read(&path).expect("real sample present");
    let outcome = open_document_bytes(&bytes, DocFormat::Gds).expect("real sample opens");

    // Frame the top cell's bbox so the render has something in view.
    let bbox = outcome
        .document
        .cell_bbox(&outcome.top_cell)
        .expect("framed cell bbox");
    let camera = Camera {
        center: reticle_geometry::Point::new(
            i32::midpoint(bbox.min.x, bbox.max.x),
            i32::midpoint(bbox.min.y, bbox.max.y),
        ),
        pixels_per_dbu: 0.05,
        viewport: bbox,
    };

    let mut renderer = WgpuRenderer::new();
    let pixels = renderer.render_document_offscreen(
        &ctx,
        &outcome.document,
        &outcome.top_cell,
        &camera,
        (128, 128),
    );
    // A 128x128 RGBA8 frame is exactly 128*128*4 bytes; reaching here proves the
    // import-to-render path did not panic.
    assert_eq!(
        pixels.len(),
        128 * 128 * 4,
        "offscreen frame is RGBA8 128x128"
    );
}
